### ISSUE TITLE
Support AMD architecture

### ISSUE THREAD

**Issue by ParkHanbum** [ememos/GiantVM#15]
kvm already support SVM which implementation of hardware-assisted virtualization for AMD. 
but it was removed from master branch. I don't know why it was. so, 
if no reason to remove it I want to recover it. 
how do you think?

**Comment by ememos** [comment]
The GiantVM paper says:
==> "On x86 platforms, Intel and AMD both have their hardware virtualization solutions. We mainly focus on Intel’s technologies in this paper."

GiantVM is not a commercial technology, but is in the elementary technology development stage.
I think that the original authors of GiantVM chose intel VT-x as their base environment to implement the idea of the paper for the first time in a limited time.

Of course, if GiantVM evolves to the commercial technology stage, multiple H/W support will be considered later.

As long as it doesn't affect the GiantVM build as it is, it doesn't seem to matter if you restore it.
