### ISSUE TITLE
linking failed 

### ISSUE THREAD

**Issue by ParkHanbum** [ememos/GiantVM#8]
I changed the header file as follow as guide.
```
m@m-desktop:~/GiantVM/QEMU-gvm-vcpupin$ sed -n 873,873p linux-headers/linux/kvm.h
#define KVM_CAP_X86_DSM 156
```

but linking fail occurred while linking qemu-system-x86_64
```
  LINK    x86_64-softmmu/qemu-system-x86_64
../interrupt-router.o: In function `qemu_io_router_thread_run_rdma':
/home/m/GiantVM/QEMU-gvm-vcpupin/interrupt-router.c:360: undefined reference to `qemu_rdma_build_incoming_file'
/home/m/GiantVM/QEMU-gvm-vcpupin/interrupt-router.c:366: undefined reference to `qemu_rdma_build_incoming_file'
../interrupt-router.o: In function `connect_io_router_rdma':
/home/m/GiantVM/QEMU-gvm-vcpupin/interrupt-router.c:406: undefined reference to `qemu_rdma_build_outcoming_file'
/home/m/GiantVM/QEMU-gvm-vcpupin/interrupt-router.c:415: undefined reference to `qemu_rdma_build_outcoming_file'
collect2: error: ld returned 1 exit status
Makefile:198: recipe for target 'qemu-system-x86_64' failed
make[1]: *** [qemu-system-x86_64] Error 1
Makefile:204: recipe for target 'subdir-x86_64-softmmu' failed
make: *** [subdir-x86_64-softmmu] Error 2
```

following is my enviroment.
```
m@m-desktop:~/GiantVM/QEMU-gvm-vcpupin$ uname -r
4.18.20-gvm1
m@m-desktop:~/GiantVM/QEMU-gvm-vcpupin$ uname -a
Linux m-desktop 4.18.20-gvm1 #1 SMP Wed Aug 11 17:05:39 KST 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ememos** [comment]
> I changed the header file as follow as guide.
> 
> ```
> m@m-desktop:~/GiantVM/QEMU-gvm-vcpupin$ sed -n 873,873p linux-headers/linux/kvm.h
> #define KVM_CAP_X86_DSM 156
> ```
> 
> but linking fail occurred while linking qemu-system-x86_64
> 
> ```
>   LINK    x86_64-softmmu/qemu-system-x86_64
> ../interrupt-router.o: In function `qemu_io_router_thread_run_rdma':
> /home/m/GiantVM/QEMU-gvm-vcpupin/interrupt-router.c:360: undefined reference to `qemu_rdma_build_incoming_file'
> /home/m/GiantVM/QEMU-gvm-vcpupin/interrupt-router.c:366: undefined reference to `qemu_rdma_build_incoming_file'
> ../interrupt-router.o: In function `connect_io_router_rdma':
> /home/m/GiantVM/QEMU-gvm-vcpupin/interrupt-router.c:406: undefined reference to `qemu_rdma_build_outcoming_file'
> /home/m/GiantVM/QEMU-gvm-vcpupin/interrupt-router.c:415: undefined reference to `qemu_rdma_build_outcoming_file'
> collect2: error: ld returned 1 exit status
> Makefile:198: recipe for target 'qemu-system-x86_64' failed
> make[1]: *** [qemu-system-x86_64] Error 1
> Makefile:204: recipe for target 'subdir-x86_64-softmmu' failed
> make: *** [subdir-x86_64-softmmu] Error 2
> ```
> 
> following is my enviroment.
> 
> ```
> m@m-desktop:~/GiantVM/QEMU-gvm-vcpupin$ uname -r
> 4.18.20-gvm1
> m@m-desktop:~/GiantVM/QEMU-gvm-vcpupin$ uname -a
> Linux m-desktop 4.18.20-gvm1 #1 SMP Wed Aug 11 17:05:39 KST 2021 x86_64 x86_64 x86_64 GNU/Linux
> ```
